name: On-demand self-hosted Huawei Cloud ECS runner for GitHub Actions
description: GitHub Action for automatic creation and registration Huawei Cloud ECS instance as a GitHub Actions self-hosted runner.
author: messense
branding:
  icon: 'box'
  color: 'orange'
inputs:
  mode:
    description: >-
      Specify here which mode you want to use:
        - 'start' - to start a new runner;
        - 'stop' - to stop the previously created runner.
    required: true
  github-token:
    description: >-
      GitHub Personal Access Token with the 'repo' scope assigned.
    required: true
  ecs-image-id:
    description: >-
      ECS Image Id (AMI). The new runner will be launched from this image.
      This input is required if you use the 'start' mode.
    required: false
  ecs-instance-type:
    description: >-
      ECS Instance Type. 
      This input is required if you use the 'start' mode.
    required: false
  subnet-id:
    description: >-
      VPC Subnet Id. The subnet should belong to the same VPC as the specified security group.
      This input is required if you use the 'start' mode.
    required: false
  security-group-id:
    description: >-
      ECS Security Group Id. 
      The security group should belong to the same VPC as the specified subnet.
      The runner doesn't require any inbound traffic. However, outbound traffic should be allowed.
      This input is required if you use the 'start' mode.
    required: false
  label:
    description: >-
      Name of the unique label assigned to the runner.
      The label is used to remove the runner from GitHub when the runner is not needed anymore.
      This input is required if you use the 'stop' mode.
    required: false
  ecs-instance-id:
    description: >-
      ECS Instance Id of the created runner.
      The id is used to terminate the ECS instance when the runner is not needed anymore.
      This input is required if you use the 'stop' mode.
    required: false
  server-tags:
    description: >-
      Tags to attach to the launched ECS instance and volume.
      This must be a stringified array of Tag objects, with both Key and Value fields,
      for example: '[{"key": "TagKey1", "value": "TagValue1"}, {"key": "TagKey2", "value": "TagValue2"}]'
    required: false
    default: '[]'
outputs:
  label:
    description: >-
      Name of the unique label assigned to the runner.
      The label is used in two cases:
      - to use as the input of 'runs-on' property for the following jobs;
      - to remove the runner from GitHub when it is not needed anymore.
  ecs-instance-id:
    description: >-
      ECS Instance Id of the created runner.
      The id is used to terminate the ECS instance when the runner is not needed anymore.
runs:
  using: node12
  main: ./dist/index.js
